declare module "*.jpg";
declare module "*.png";
declare module "*.jpeg";
declare module "*.svg";
declare module "styled-components";
declare module "*.ttf";
declare module "react-router-dom";
declare module "react-modal";
declare module "react-use-cart"